### ISSUE TITLE
Playlist View Shortcuts

### ISSUE THREAD

**Issue by yougotwill** [maculateConception/aural-player#15]
Love this player and keep up the amazing work! 💪 

Could we get shortcuts to toggle between the different playlists views (Tracks, Artists, Albums, Genres) please?  I have thought of 2 options for the key combinations.

1. Cmd+Alt+Left/Right to cycle through the different playlist views.
2. Cmd+Shift+1/2/3/4 changes to the corresponding view.

Thanks in advance! :)

**Comment by maculateConception** [comment]
Your wish has been granted, Sir ! Thank you for the suggestion and feedback.

[Latest release](https://github.com/maculateConception/aural-player/releases/tag/1.6.1)

I did a fair bit of research and experimentation to find suitable keyboard shortcuts. I concluded that Shift+Cmd+[ and ] would be the best, as they are already used by various well known macOS apps - Finder, Firefox, Chrome to switch tabs, so they will be more intuitive to users.

Previous playlist view - Shift + Cmd + [
Next playlist view - Shift + Cmd + ]

Note that I have also made these ^ the standard shortcuts for all Aural Player dialog windows and popovers. This is all clearly documented on the release page.

Thanks **_again_** for contributing to the project ... I remember your username from earlier :)

**Comment by yougotwill** [comment]
Amazing! That was very quick, thank you :) Everything works great! ... A very small detail I noticed is that the keybindings don't apply to the effects window. Everything else is perfect 👍

**Comment by yougotwill** [comment]
I'll close this issue for now since the above is related to keyboard navigation and not the playlist window.

**Comment by maculateConception** [comment]
Yes, good observation. I thought about it long and hard and here's the problem - you can only bind the same shortcuts to one use case.

In fact, the way I had thought of doing it earlier was that the shortcuts would apply to the currently active window. So, if you were using the effects window, it will switch tabs there.

The issue with this above approach is that the shortcut requires a certain window to be active before it works there. So, let's say you're using the player window and suddenly want to switch tabs on the playlist window. You will have to first make the playlist window active by clicking on it. This additional step is an inconvenience to users and makes the shortcut less intuitive, worsening the user experience.

I weighed the pros and cons and concluded that the effects window tabs are probably not switched that frequently by users (I could be wrong). So, I assigned those shortcuts to only the playlist window.

Another simple way to solve this problem is to simply assign different shortcuts to switch effects window tabs ... what do you think ?

**Comment by yougotwill** [comment]
I understand the issue in that case might I suggest a variation of the same keyboard combination for example `Cmd+[` and `Cmd + ]` for cycling through the tabs on the effects window and then keeping the regular shortcuts as is. While not ideal it at least keeps the shortcut combination for "cycling through tabs" consistent with the `Shift` being the modifier key to differentiate between the two.

**Comment by yougotwill** [comment]
For the record, you could also use this shortcut idea if you ever have two sets of panels on one window in the future!

`Cmd+Shift+{` and `Cmd+Shift+}` - Cycle through parent panel
`Cmd+[` and `Cmd+]` - Cycle through child or alternative panel

**Comment by maculateConception** [comment]
Yup, thanks for the ideas. 

I will have to do some more serious thinking and experimentation and try to come up with something intuitive and effective.

Keep your feature suggestions coming :) I have suddenly found some time to allocate to this project so I will be working on it for some time to come, I think.

**Comment by maculateConception** [comment]
I forgot to mention one other thing. If you have a trackpad surface (i.e. on a Macbook), there are Trackpad gestures recognized by Aural Player, to switch between playlist views and perform other functions. I really should document this somewhere like the Wiki.

Player functions: (mouse cursor must be over player window)

- Previous / Next track: 3 finger horizontal swipe
- Seek backward / forward: 2 finger horizontal swipe
- Volume up / down: 2 finger vertical swipe

Playlist functions (mouse cursor must be over playlist window)

- Switch playlist views: 3 finger horizontal swipe
- Scroll to top / bottom of playlist: 3 finger vertical swipe
- Scroll up / down: 2 finger vertical swipe

**Comment by yougotwill** [comment]
That's good to know. Thank you 🙏
