### ISSUE TITLE
ffmpeg.c, ffmpeg.h, config.h (after compilation of ffmpeg) are missing from source code tree

### ISSUE THREAD

**Issue by hemmlj** [maculateConception/aural-player#26]
The files "ffmpeg.h" and "ffmpeg.c" are missing from the source code tree as ffmpeg v4.3.1 is delivered as "ffmpeg-sourceCode.bz2" in Resources/ffmpeg folder. So compiling for ffmpeg needs to be done with build-ffmpeg.sh (read the README.txt in Resources/ffmpeg folder). So far, so fine. But afterwards "config.h" is still missing! Please note where to find that file. Thanks!

**Comment by maculateConception** [comment]
Hi, thanks so much for letting me know about this ! Those 2 files were being referenced from a duplicate project somewhere else on my hard drive, so I didn't catch the error before this.

I have added those 2 files now under Aural/Source. Please refer to [this Git commit](https://github.com/maculateConception/aural-player/commit/51a31ba067ddb05909d7945200602488b58009f7).

Cheers !

**Comment by hemmlj** [comment]
OK that issues seems to be solved now.

**Comment by maculateConception** [comment]
Cool, thanks for letting me know.

I found that config.h was referenced from some of the ffmpeg C code (as an #include), but I think the reason the code compiles without the file present is because it looks like a conditional include:

`#ifdef HAVE_AV_CONFIG_H

#include "config.h"`

Anyway, glad it's all fixed now. I've closed the issue.

Cheers !

**Comment by hemmlj** [comment]
It definitely compiles now. Thank you!
