### ISSUE TITLE
auxMixer

### ISSUE THREAD

**Issue by terenzeyuen** [maculateConception/aural-player#3]
Great work! I noticed in initPlayer you reconnectNodes to auxMixer instead of mainMixer. Any reasons for it as I can't seem to find any place in code that uses auxMixer (yet)?

**Comment by maculateConception** [comment]
Hi Terenz,

Thanks for your feedback. Yes, I reconnect playerNode to aux mixer because the aux mixer is responsible for performing sample rate conversions and channel count conversions.

I cannot do this with main mixer, because there are other nodes (EQ, Pitch, etc), between the player and main mixer, so I had to insert an aux mixer to perform the conversions.

Hope this helps !

**Comment by terenzeyuen** [comment]
Thank you very much @maculateConception
