### ISSUE TITLE
Aural 3.5.1 crashes on selecting "Manage effects presets"

### ISSUE THREAD

**Issue by LesterJitsi** [maculateConception/aural-player#35]
As per title, I was fiddling about looking for a way to edit an equalizer preset's title I had saved* and every time I selected _Sound > Manage effects presets_ (either with trackpad or shortcut) Aural crashed immediately. I actually didn't mean to manage effects presets, I was just exploring menus. After the first crash I couldn't find anymore the equalizer preset I had saved and Aural didn't retain the playlist I was listening to, but the previous one. I think you can find all needed info in the logs I'm attaching. TIA

* btw, how can I edit a title I had mistyped?

[logs.zip](https://github.com/maculateConception/aural-player/files/8010781/logs.zip)

**Comment by maculateConception** [comment]
Thanks for reporting the bug ! You're running macOS Mojave, right ?

I was able to reproduce the crash on my system with v3.5.1 ... this is a very bad bug ! My bad.

To edit an EQ preset's title, you are correct - you would go the menu **Sound > Manage effects presets**.

When it actually works and shows up fine, what you would do is go to the EQ tab, then select the preset you want to edit from the list of EQ presets, and either click on it once, or click the _Rename_ button. That should place focus on the text field in which you can type a new name.

I will work on releasing a fix ASAP (possibly tonight !).

**Comment by LesterJitsi** [comment]
Yes, Mojave and I'm sorry to learn that v. 4.0 will work only on 11.x and newer, since I don't plan to upgrade my system any time soon. I understand though, of course. Version 3 is already very good.

**Comment by maculateConception** [comment]
That's too bad, and I'm sorry about that :-( 

There are 2 main reasons why v4.0 will stop supporting older systems:

1 - To take advantage of some newer AppKit APIs that are only available on newer systems. This would hugely simplify source code maintenance.
2 - Because I am a one man army working on this project and don't have time to test the app on so many different OS versions.

Hope that makes some sense.

BTW, I have already fixed the crash and will release v3.5.2 in the next few minutes.

---------------------------------------------

Here is a GIF demonstrating how to rename an FX preset:

![fxPreset-edit](https://user-images.githubusercontent.com/30028539/152695268-844ba3e2-f1b1-4f9a-873e-72458dc97a6b.gif)

**Comment by LesterJitsi** [comment]
> Hope that makes some sense.

Of course it does.

Thank you so much. Wish I could help you but I'm clueless about developing.

**Comment by maculateConception** [comment]
I have released [version 3.5.2](https://github.com/maculateConception/aural-player/releases/tag/v3.5.2). I have mentioned your name on the release page. I appreciate you reporting this bug 👍 .

Please try it out and let me know if you were able to edit presets successfully ! Sorry about the crash and about you losing your saved data. In later releases, I hope to solve that issue too ... a crash should not cause the previous app state to be lost.

**Comment by maculateConception** [comment]
I just found another second crash in the FX presets editor and have fixed that too - same reason as the first crash.

I have updated the release app bundle after the initial release. Please re-download the latest app bundle from the same v.3.5.2 page. Sorry about that !

These crashes were caused by some recent enhancements to the Time Stretch FX unit.

**Comment by LesterJitsi** [comment]
The second release works fine. When the Effects Presets window is open it stays on foreground when I shift to a different application (see screenshot). Is this meant?
![snapshot](https://user-images.githubusercontent.com/25617355/152696632-0a77f057-754b-4b00-a075-261d222afdab.jpg)

**Comment by maculateConception** [comment]
Great, thanks for reporting that it works !

Yes, that behavior is as (currently) designed, because the editor window is a **_modal window_**. So, it requires the user to click **_Done_** before switching to another app or continuing to use Aural.

But, now that you mentioned it, perhaps that should not be a modal window :-) I will note it down for a future release !
